general:
  label: 基础设置
  items:
    sub_title:
      name: sub_title
      label: 二级标题
      type: text
      default: 'the site subtitle'
    footer_slogan:
      name: footer_slogan
      label: 页脚标语
      type: text
      default: '我的精神家园'
    enable_mathJax:
      name: enable_mathJax
      label: 是否使用 MathJax
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    enable_summary:
      name: enable_summary
      label: 是否显示文章摘要
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    custom_css:
      name: custom_css
      label: 自定义样式
      type: textarea
sns:
  label: 社交资料
  items:
    github:
      name: github
      label: Github
      type: text
    twitter:
      name: twitter
      label: Twitter
      type: text
    facebook:
      name: facebook
      label: Facebook
      type: text
    weibo:
      name: weibo
      label: Weibo
      type: text
    instagram:
      name: instagram
      label: Instagram
      type: text